config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :properties

end

app/models/property.rb
class Property < ActiveRecord::Base
	geocoded_by :street
	after_validation :geocode
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
	require 'open-uri'
	require 'nokogiri'
	require 'mechanize'
  def index
    @properties = Property.all
    @property=Property.last
    @hash = Gmaps4rails.build_markers(@properties) do |property, marker|
    	if(property.latitude!=nil)
			  marker.lat property.latitude
			  marker.lng property.longitude
			  marker.infowindow property.street
			end
		end
		@agent = Mechanize.new
		@mechdoc= @agent.get('http://offcampus.osu.edu/search-housing.aspx')
		@docstring=""
		i =1
		while i <1
			@doc = Nokogiri::HTML(open("http://offcampus.osu.edu/search-housing.aspx?page="+i.to_s))

			@doc.css("div.preview div.header h3 a").each do |node|
					@docproperty=Property.new
					@docproperty.street=node.text+" columbus Ohio USA 43201"
					@docstring+=node.text
			end
			i+=1
		end
  end
 
  def show
    @property = Property.find(params[:id])
  end
 
  def new
    @property = Property.new
  end
 
  def edit
    @property = Property.find(params[:id])
  end
 
  def create
    @property = Property.new(property_params)
 
    if @property.save
      redirect_to @property
    else
      render 'new'
    end
  end
 
  def update
    @property = Property.find(params[:id])
 
    if @property.update(property_params)
      redirect_to @property
    else
      render 'edit'
    end
  end
 
  def destroy
    @property = Property.find(params[:id])
    @property.destroy
 
    redirect_to properties_path
  end
 
  private
    def property_params
      params.require(:property).permit(:name, :description,:street,:latitude,:longitude)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Housing</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/properties/edit.html.erb
<h1>Editing property</h1>
 
<%= form_for :property, url: property_path(@property), method: :patch do |f| %>
 
  <% if @property.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@property.errors.count, "error") %> prohibited
        this property from being saved:
      </h2>
      <ul>
        <% @property.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>
 
  <p>
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </p>

  <p>
    <%= f.label :bedrooms  %><br>
    <%= f.text_field :bedrooms %>
  </p>

  <p>
    <%= f.label :bathrooms %><br>
    <%= f.text_field :bathrooms %>
  </p>

  <p>
    <%= f.label :type %><br>
    <%= f.text_field :type %>
  </p>
 
  <p>
    <%= f.label :landlord %><br>
    <%= f.text_field :landlord %>
  </p>

  <p>
    <%= f.label :parking  %><br>
    <%= f.text_field :parking %>
  </p>

  <p>
    <%= f.label :pet %><br>
    <%= f.text_field :pet %>
  </p>

  <p>
    <%= f.label :street %><br>
    <%= f.text_field :street %>
  </p>
 
  <p>
    <%= f.label :xcoordinate %><br>
    <%= f.text_field :xcoordinate %>
  </p>

  <p>
    <%= f.label :ycoordinate  %><br>
    <%= f.text_field :ycoordinate %>
  </p>f.text_area :description %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>
 
<%= link_to 'Back', properties_path %>

app/views/properties/index.html.erb
 
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
  <div>
  <body>
<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
<div class="row">
  <div id="map" style='width: 50%; height: 400px;'></div>

<script type="text/javascript">

handler = Gmaps.build('Google');
handler.buildMap({ provider: {
    zoom: 5,

}, internal: {id: 'map'}}, function(){
  markers = handler.addMarkers(<%=raw @hash.to_json %>);

  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
});
</script>




    <script>
function initialize() {

  var panoramaOptions = {
    position: new google.maps.LatLng(40.010849, -83.000096),
    pov: {
      heading: 34,
      pitch: 10
    }
  };
  var panorama = new google.maps.StreetViewPanorama(document.getElementById('pano'), panoramaOptions);
  map.setStreetView(panorama);
}

google.maps.event.addDomListener(window, 'load', initialize);

    </script>
    <div id="pano" style="position:absolute; top:0px;right:0px; width: 50%; height: 400px;"></div>
  </body></div></div>
  <h1><%=@docstring%></h1>
  <table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Price</th>
    <th>Bedrooms</th>
    <th>Bathrooms</th>
    <th>Type</th>
    <th>Landlord</th>
    <th>Parking</th>
    <th>Pet</th>
    <th colspan="2"></th>
  </tr>
 
  <% @properties.each do |property| %>
    <tr>
      <td><%= property.name%></td>
      <td><%= property.description %></td>
      <td><%= property.price %></td>
      <td><%= property.bedrooms %></td>
      <td><%= property.bathrooms %></td>
      <td><%= property.type %></td>
      <td><%= property.landlord %></td>
      <td><%= property.parking %></td>
      <td><%= property.pet %></td>
      <td><%= link_to 'Show', property_path(property) %></td>
      <td><%= link_to 'Edit', edit_property_path(property) %></td>
    </tr>
  <% end %>
</table>

<%= link_to 'New Property', new_property_path %>

app/views/properties/new.html.erb
<%= form_for :property, url: properties_path do |f| %>
 
  <% if @property.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@property.errors.count, "error") %> prohibited
        this property from being saved:
      </h2>
      <ul>
        <% @property.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>
 
  <p>
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </p>

  <p>
    <%= f.label :bedrooms  %><br>
    <%= f.text_field :bedrooms %>
  </p>

  <p>
    <%= f.label :bathrooms %><br>
    <%= f.text_field :bathrooms %>
  </p>

  <p>
    <%= f.label :type %><br>
    <%= f.text_field :type %>
  </p>
 
  <p>
    <%= f.label :landlord %><br>
    <%= f.text_field :landlord %>
  </p>

  <p>
    <%= f.label :parking  %><br>
    <%= f.text_field :parking %>
  </p>

  <p>
    <%= f.label :pet %><br>
    <%= f.text_field :pet %>
  </p>

  <p>
    <%= f.label :street %><br>
    <%= f.text_field :street %>
  </p>
 
  <p>
    <%= f.label :xcoordinate %><br>
    <%= f.text_field :xcoordinate %>
  </p>

  <p>
    <%= f.label :ycoordinate  %><br>
    <%= f.text_field :ycoordinate %>
  </p>

  <p>
    <%= f.submit %>
  </p>
 
<% end %>
 
<%= link_to 'Back', properties_path %>

app/views/properties/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @property.name %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @property.description %>
</p>

<%= link_to 'Back', properties_path %> |
<%= link_to 'Edit', edit_property_path(@property) %>

app/views/welcome/index.html.erb
 
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
  <div>
  <body>
<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>
    <script>
function createSidebarLi(json){
  return ("<li><a>" + json.name + "</a></li>");
};

function bindLiToMarker($li, marker){
  $li.on('click', function(){
    handler.getMap().setZoom(14);
    marker.setMap(handler.getMap()); //because clusterer removes map property from marker
    marker.panTo();
    google.maps.event.trigger(marker.getServiceObject(), 'click');
  })
};

function createSidebar(json_array){
  _.each(json_array, function(json){
    var $li = $( createSidebarLi(json) );
    $li.appendTo('#sidebar_container');
    bindLiToMarker($li, json.marker);
  });
};

handler = Gmaps.build('Google');
handler.buildMap({ internal: {id: 'sidebar_builder'}}, function(){
  var json_array = [
    { lat: 40, lng: -80, name: 'Foo', infowindow: "I'm Foo" },
    { lat: 45, lng: -90, name: 'Bar', infowindow: "I'm Bar" },
    { lat: 50, lng: -85, name: 'Baz', infowindow: "I'm Baz" }
  ];

  var markers = handler.addMarkers(json_array);

  _.each(json_array, function(json, index){
    json.marker = markers[index];
  });

  createSidebar(json_array);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
});
    
</script>
<div style='width: 800px;'>
  <div id="sidebar_builder" style='width: 800px; height: 400px;'></div>
</div>
<div id='sidebar_container'>
</div>